/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
*/

#include <stdio.h>

int main(){

	int t = 4000000;

	int fll = 0;
	int fl = 0;
	int f = 1;

	int sum = 0;

	while (f <= t){

		printf("%d",f);

		fll = fl;
		fl = f;
		f = fl + fll;

		if (f % 2 == 0){
			printf("*\n");
			sum = sum + f;
		}

		else{
			printf("\n");
		}
	}

	printf("\n\n");
	printf("%d\n", sum);
}



// [fll]-->[fl]-->[f]