/*

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; 
what is the value of D?

*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <time.h>

int main()
{
	clock_t start = clock();

	int pents[30000];

	for (int n = 1; n < 20000; n++){
		pents[n-1] = n*(3*n-1)/2;
		//if (n<20) printf("%d\n", pents[n-1]);
	}

	int a, b;

	for (a = 0; a < 2200; a++){

		if (a % 200 == 0 && b % 2000 == 0){
			printf("*\n");
		}

		for (b = 2200; b > 0; b--){




			int sum = pents[a] + pents[b];
			int dif = pents[a] - pents[b];

			int i = 0;
			int k = 0;

			while (pents[i] <= sum){

				if (pents[i] == sum){

					while (pents[k] <= dif){

						if (pents[k] == dif && i != k){
							printf("\n[P_%d = %d][P_%d = %d]\n[Sum = %d = P_%d] | [Diff = %d = P_%d]\n\n", 
								a+1, pents[a], b+1, pents[b], pents[i], i+1, pents[k], k+1);
							printf("ans: %d\n\n", pents[k]);
						}

						k++;

					}
				}

				i++;

			}

		}
	}











	clock_t end = clock();
	double time_spent = (double)(end - start) / CLOCKS_PER_SEC;
	printf("found in %fs\n", time_spent);

}
