/*

The sequence of triangle numbers is generated by adding the natural numbers.

So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

*/

#include <stdio.h>
#include <math.h>



int factors(triangle_n)
{

	long factor = 0;
	int numfactors = 0;

	for (factor = 1; factor <= sqrt(triangle_n); factor++)
	{
		if (triangle_n % factor == 0){
			numfactors = numfactors + 2;
		}
	}

	//printf("%d\n", numfactors);

	return numfactors;
}



int main()
{

	long triangle_n = 0;
	long triangle_n_factors = 0;

	long n = 0;

	int largest = 0;

	//list triangle numbers and numfactors
	while (triangle_n_factors < 501){

		triangle_n = triangle_n + n;

		n = n+1;

		triangle_n_factors = factors(triangle_n);

		if (triangle_n_factors > largest){

			printf("%ld, #%ld, factors: %ld\n", triangle_n, n, triangle_n_factors);
			largest = triangle_n_factors;
		}

		if (n % 100 == 0){

			printf("%ld\n", n);

		}

	}

}
